### ISSUE TITLE
Remove degit dependency in favour of Github feature "Template Repository"

### ISSUE THREAD

**Issue by lbrutti** [ONSvisual/svelte-scrolly#1]
Hello and thanks for this great boilerplate.
It would be very nice if you remove the dependency of `degit` package with the above mentioned github feature.

To enable it you just need to go to the repo setting and check the flag:
<img width="1091" alt="Location of template repository flag in settings page" src="https://user-images.githubusercontent.com/5331258/166092949-0924f08c-0fc6-4c2f-91ff-4062891aa6a6.png">

This will add the "Use this template" button to the repo homepage:
<img width="918" alt="Use this template button in repository home page" src="https://user-images.githubusercontent.com/5331258/166093050-c11a3aac-0638-4a34-a7ff-de5213852fb3.png">

Thanks,
Lorenzo

**Comment by henryjameslau** [comment]
Hi @lbrutti,
That feature has now be enabled.
Henry

**Comment by jtrim-ons** [comment]
Should we update the README too, or is degit still helpful for some use cases?

**Comment by lbrutti** [comment]
I think it may still be a fallback for people that don't have a GitHub
account... Maybe an edit highlighting that, for GitHub users, the "use this
template" is suggested.

--
Inviato da Android

Il Gio 5 Mag 2022, 10:35 jtrim-ons ***@***.***> ha scritto:
